/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controller.Criticos;
import controller.controller.Libros;
import controller.controller.Masivos;
import controller.controller.Normales;

/**
 *
 * @author cristiancg
 */
public class ListarLibros extends javax.swing.JFrame {

    Libros lib = new Libros();
    Criticos cri = new Criticos();
    Masivos mas = new Masivos();
    Normales nor = new Normales();

    public ListarLibros() {
        initComponents();
        setLocationRelativeTo(null);
        lib.mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnMasivos = new javax.swing.JButton();
        btnNormales = new javax.swing.JButton();
        bynCriticos = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        btnModificarLibro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Libros", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Math TeX Gyre", 1, 14))); // NOI18N

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaLibros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Math TeX Gyre", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMasivos.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        btnMasivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/negocio (1).png"))); // NOI18N
        btnMasivos.setText("MASIVOS");
        btnMasivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMasivos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMasivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasivosActionPerformed(evt);
            }
        });
        jPanel2.add(btnMasivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btnNormales.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        btnNormales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfaz.png"))); // NOI18N
        btnNormales.setText("NORMALES");
        btnNormales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNormales.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnNormales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalesActionPerformed(evt);
            }
        });
        jPanel2.add(btnNormales, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        bynCriticos.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        bynCriticos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/educaciones.png"))); // NOI18N
        bynCriticos.setText("CRITICOS");
        bynCriticos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bynCriticos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bynCriticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bynCriticosActionPerformed(evt);
            }
        });
        jPanel2.add(bynCriticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        btnEliminarLibro.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        btnEliminarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconborro.png"))); // NOI18N
        btnEliminarLibro.setText("ELIMINAR");
        btnEliminarLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarLibro.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        btnModificarLibro.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        btnModificarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orientacion.png"))); // NOI18N
        btnModificarLibro.setText("MODIFICAR");
        btnModificarLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarLibro.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(btnModificarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bynCriticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bynCriticosActionPerformed
        cri.tablaLibrosCriticos();
    }//GEN-LAST:event_bynCriticosActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
       lib.eliminarLibro();
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void btnMasivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasivosActionPerformed
        mas.tablaLibrosMasivos();
    }//GEN-LAST:event_btnMasivosActionPerformed

    private void btnNormalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalesActionPerformed
       nor.tablaLibrosNormales();
    }//GEN-LAST:event_btnNormalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnMasivos;
    private javax.swing.JButton btnModificarLibro;
    private javax.swing.JButton btnNormales;
    private javax.swing.JButton bynCriticos;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablaLibros;
    // End of variables declaration//GEN-END:variables

}
