/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author cristiancg
 */
public class MenuJF extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MenuJF() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReservar = new javax.swing.JButton();
        btnPrestar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDevolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        ItemRegistrar = new javax.swing.JMenuItem();
        ItemListar = new javax.swing.JMenuItem();
        menuRegistro = new javax.swing.JMenu();
        ItemRegistrarLibro = new javax.swing.JMenuItem();
        ItemListarLibros = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ItemConsultar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReservar.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/presto.png"))); // NOI18N
        btnReservar.setText("RESERVAR");
        btnReservar.setBorderPainted(false);
        btnReservar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReservar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 110, 60));

        btnPrestar.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        btnPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/instruccion.png"))); // NOI18N
        btnPrestar.setText("PRESTAR ");
        btnPrestar.setBorderPainted(false);
        btnPrestar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrestar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 110, 60));

        jLabel3.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("BIBLIOTECA VIRTUAL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BIENVENIDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 320, 50));

        btnDevolver.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/el-fin.png"))); // NOI18N
        btnDevolver.setText("DEVOLVER");
        btnDevolver.setBorderPainted(false);
        btnDevolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDevolver.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 110, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quizas.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        menuUsuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grupo.png"))); // NOI18N
        menuUsuarios.setText("USUARIOS");
        menuUsuarios.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N

        ItemRegistrar.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        ItemRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/useradd.png"))); // NOI18N
        ItemRegistrar.setText("REGISTRAR");
        ItemRegistrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ItemRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRegistrarActionPerformed(evt);
            }
        });
        menuUsuarios.add(ItemRegistrar);

        ItemListar.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        ItemListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/puntuacion.png"))); // NOI18N
        ItemListar.setText("LISTAR");
        ItemListar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarActionPerformed(evt);
            }
        });
        menuUsuarios.add(ItemListar);

        jMenuBar1.add(menuUsuarios);

        menuRegistro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/leyendo.png"))); // NOI18N
        menuRegistro.setText("REGISTRO DE LIBROS");
        menuRegistro.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N

        ItemRegistrarLibro.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        ItemRegistrarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/favorito.png"))); // NOI18N
        ItemRegistrarLibro.setText("REGISTRAR");
        ItemRegistrarLibro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ItemRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRegistrarLibroActionPerformed(evt);
            }
        });
        menuRegistro.add(ItemRegistrarLibro);

        ItemListarLibros.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        ItemListarLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/puntuacion.png"))); // NOI18N
        ItemListarLibros.setText("LISTAR LIBROS");
        ItemListarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarLibrosActionPerformed(evt);
            }
        });
        menuRegistro.add(ItemListarLibros);

        jMenuBar1.add(menuRegistro);

        jMenu3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarlibro.png"))); // NOI18N
        jMenu3.setText("CONSUTA DE LIBROS");
        jMenu3.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N

        ItemConsultar.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        ItemConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro.png"))); // NOI18N
        ItemConsultar.setText("CONSULTAR LIBRO");
        ItemConsultar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ItemConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemConsultarActionPerformed(evt);
            }
        });
        jMenu3.add(ItemConsultar);

        jMenuItem1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cheque.png"))); // NOI18N
        jMenuItem1.setText("CONSULTAR RESERVA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/senales.png"))); // NOI18N
        jMenu4.setText("SALIR");
        jMenu4.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N

        ItemSalir.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 10)); // NOI18N
        ItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/senales.png"))); // NOI18N
        ItemSalir.setText("OK");
        ItemSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSalirActionPerformed(evt);
            }
        });
        jMenu4.add(ItemSalir);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRegistrarActionPerformed
        JFregistrarUsuario reg = new JFregistrarUsuario();
        reg.setVisible(true);
    }//GEN-LAST:event_ItemRegistrarActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
       PrestarLibro pres = new PrestarLibro();
       pres.setVisible(true); 
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        ReservarLibro rese = new ReservarLibro();
        rese.setVisible(true);
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        DevolverLibro devo= new DevolverLibro();
        devo.setVisible(true);
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void ItemRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRegistrarLibroActionPerformed
       RegistroLibros regi = new RegistroLibros();
       regi.setVisible(true);
    }//GEN-LAST:event_ItemRegistrarLibroActionPerformed

    private void ItemConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemConsultarActionPerformed
        ConsultarLibros consu = new ConsultarLibros();
        consu.setVisible(true);
    }//GEN-LAST:event_ItemConsultarActionPerformed

    private void ItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_ItemSalirActionPerformed

    private void ItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarActionPerformed
        ListarUsuarios list = new ListarUsuarios();
        list.setVisible(true);
    }//GEN-LAST:event_ItemListarActionPerformed

    private void ItemListarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarLibrosActionPerformed
        ListarLibros list = new ListarLibros();
        list.setVisible(true);
    }//GEN-LAST:event_ItemListarLibrosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ConsultarReserva ver = new ConsultarReserva();
        ver.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemConsultar;
    private javax.swing.JMenuItem ItemListar;
    public static javax.swing.JMenuItem ItemListarLibros;
    private javax.swing.JMenuItem ItemRegistrar;
    private javax.swing.JMenuItem ItemRegistrarLibro;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JMenu jMenu3;
    public static javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenu menuRegistro;
    public static javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables


    
}
