/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquinacafe.vista;

/**
 *
 * @author cristiancg
 */
public class Vista extends javax.swing.JFrame {

    int producto, boton, dinero;
    
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnexpreso = new javax.swing.JButton();
        btnristretto = new javax.swing.JButton();
        btncortado = new javax.swing.JButton();
        btnamericano = new javax.swing.JButton();
        btncarajillo = new javax.swing.JButton();
        btnconleche = new javax.swing.JButton();
        btnbombon = new javax.swing.JButton();
        btncapuchino = new javax.swing.JButton();
        btnmocca = new javax.swing.JButton();
        btnirlandes = new javax.swing.JButton();
        btnvienes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnfrape = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        txtingresarmonto = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtmostrar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btncobrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnexpreso.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnexpreso.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/cafe.png")); // NOI18N
        btnexpreso.setText("EXPRESO 2.0 € ");
        btnexpreso.setToolTipText("");
        btnexpreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnexpreso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnexpreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpresoActionPerformed(evt);
            }
        });
        getContentPane().add(btnexpreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 60));

        btnristretto.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnristretto.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/cafe (1).png")); // NOI18N
        btnristretto.setText("RISTRETTO 2.3 € ");
        btnristretto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnristretto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnristretto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnristrettoActionPerformed(evt);
            }
        });
        getContentPane().add(btnristretto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 60));

        btncortado.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btncortado.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/vaso-desechable.png")); // NOI18N
        btncortado.setText("MACCHIATO 2.5 € ");
        btncortado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncortado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncortado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncortadoActionPerformed(evt);
            }
        });
        getContentPane().add(btncortado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 60));

        btnamericano.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnamericano.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/taza-de-cafe.png")); // NOI18N
        btnamericano.setText("AMERICANO 3.0 € ");
        btnamericano.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnamericano.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnamericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnamericanoActionPerformed(evt);
            }
        });
        getContentPane().add(btnamericano, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 60));

        btncarajillo.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btncarajillo.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/cafe (2).png")); // NOI18N
        btncarajillo.setText("CARAJILLO 3.3 € ");
        btncarajillo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncarajillo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncarajillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncarajilloActionPerformed(evt);
            }
        });
        getContentPane().add(btncarajillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 140, 60));

        btnconleche.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnconleche.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/cafe (4).png")); // NOI18N
        btnconleche.setText("CON LECHE 3.9 € ");
        btnconleche.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnconleche.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnconleche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconlecheActionPerformed(evt);
            }
        });
        getContentPane().add(btnconleche, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 140, 60));

        btnbombon.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnbombon.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/te.png")); // NOI18N
        btnbombon.setText("BOMBON 2.5 € ");
        btnbombon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbombon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbombon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbombonActionPerformed(evt);
            }
        });
        getContentPane().add(btnbombon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 140, 60));

        btncapuchino.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btncapuchino.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/capuchino.png")); // NOI18N
        btncapuchino.setText("CAPUCHINO 4.5 € ");
        btncapuchino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncapuchino.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncapuchino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapuchinoActionPerformed(evt);
            }
        });
        getContentPane().add(btncapuchino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 140, 60));

        btnmocca.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnmocca.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/capuchino (2).png")); // NOI18N
        btnmocca.setText("MOCCA 4.0 € ");
        btnmocca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmocca.setVerifyInputWhenFocusTarget(false);
        btnmocca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmocca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoccaActionPerformed(evt);
            }
        });
        getContentPane().add(btnmocca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 140, 60));

        btnirlandes.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnirlandes.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/cafe (3).png")); // NOI18N
        btnirlandes.setText("IRLANDES 6.0 € ");
        btnirlandes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnirlandes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnirlandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnirlandesActionPerformed(evt);
            }
        });
        getContentPane().add(btnirlandes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 140, 60));

        btnvienes.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnvienes.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/para-llevar.png")); // NOI18N
        btnvienes.setText("VIENES 4.5 € ");
        btnvienes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnvienes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnvienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvienesActionPerformed(evt);
            }
        });
        getContentPane().add(btnvienes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 140, 60));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIPOS DE CAFE");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 200, 40));

        btnfrape.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnfrape.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/frape.png")); // NOI18N
        btnfrape.setText("FRAPE 5.0 € ");
        btnfrape.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnfrape.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnfrape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfrapeActionPerformed(evt);
            }
        });
        getContentPane().add(btnfrape, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 140, 60));

        jLabel3.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADICIONES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 90, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/vaca (1).png")); // NOI18N
        jButton1.setText("LECHE");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 120, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/crema-batida.png")); // NOI18N
        jButton2.setText("CREMA");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 120, -1));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/dulce.png")); // NOI18N
        jButton3.setText("NATA");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 120, -1));

        jButton4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/espiritu.png")); // NOI18N
        jButton4.setText("WISKEY");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 120, -1));

        jButton14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/whisky.png")); // NOI18N
        jButton14.setText("BRANDY");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 120, -1));

        jButton15.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/canela.png")); // NOI18N
        jButton15.setText("CANELA");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 120, -1));

        jButton16.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/cacao.png")); // NOI18N
        jButton16.setText("CHOCOLATE");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 120, -1));

        jButton17.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/leche.png")); // NOI18N
        jButton17.setText("LECHE CON");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 120, -1));

        jButton18.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/soltar.png")); // NOI18N
        jButton18.setText("AGUA");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 120, 40));

        jButton19.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/hielo.png")); // NOI18N
        jButton19.setText("HIELO");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 120, -1));

        jButton20.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/verano.png")); // NOI18N
        jButton20.setText("HELADO");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 120, -1));

        txtingresarmonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingresarmontoActionPerformed(evt);
            }
        });
        txtingresarmonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtingresarmontoKeyTyped(evt);
            }
        });
        getContentPane().add(txtingresarmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 180, 30));

        jButton21.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon("/home/cristiancg/Descargas/azucar.png")); // NOI18N
        jButton21.setText("Azucar");
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 384, 120, 40));

        jLabel4.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel4.setText("INGRESE EL MONTO $");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        txtmostrar.setEditable(false);
        txtmostrar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtmostrar.setToolTipText("");
        txtmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(txtmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 210, 90));

        jLabel5.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DETALLES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        btncobrar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btncobrar.setText("COBRO");
        btncobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maquinacafe/vista/cafe.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 540));

        jMenu1.setText("File");

        jMenuItem1.setText("salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnconlecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconlecheActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe con leche "+ 3.9 + "€ ");
    }//GEN-LAST:event_btnconlecheActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void txtingresarmontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingresarmontoActionPerformed
        
    }//GEN-LAST:event_txtingresarmontoActionPerformed

    private void btnexpresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexpresoActionPerformed
        producto= producto +1;
        boton =1;
        txtmostrar.setText(txtmostrar.getText() + "Cafe Expreso "+ 2.0 + "€ ");
    }//GEN-LAST:event_btnexpresoActionPerformed

    private void txtmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmostrarActionPerformed

    private void txtingresarmontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtingresarmontoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtingresarmontoKeyTyped

    private void btnristrettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnristrettoActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe Ristretto"+ 2.3 + "€ ");
    }//GEN-LAST:event_btnristrettoActionPerformed

    private void btncortadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncortadoActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe Cortado "+ 2.5 + "€ ");
    }//GEN-LAST:event_btncortadoActionPerformed

    private void btnamericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnamericanoActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe Americano "+ 3.0 + "€ ");
    }//GEN-LAST:event_btnamericanoActionPerformed

    private void btncarajilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncarajilloActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe Expreso "+ 2.3 + "€ ");
    }//GEN-LAST:event_btncarajilloActionPerformed

    private void btnbombonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbombonActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe Bombon"+ 2.5 + "€ ");
    }//GEN-LAST:event_btnbombonActionPerformed

    private void btncapuchinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapuchinoActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe Capuchino "+ 4.5 + "€ ");
    }//GEN-LAST:event_btncapuchinoActionPerformed

    private void btnmoccaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoccaActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe Mocca "+ 4.0 + "€ ");
    }//GEN-LAST:event_btnmoccaActionPerformed

    private void btnirlandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnirlandesActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe Irlandes "+ 6.0 + "€ ");
    }//GEN-LAST:event_btnirlandesActionPerformed

    private void btnvienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvienesActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe Vienes "+ 4.5 + "€ ");
    }//GEN-LAST:event_btnvienesActionPerformed

    private void btnfrapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfrapeActionPerformed
        txtmostrar.setText(txtmostrar.getText() + "Cafe Frapeado "+ 5.0 + "€ ");
    }//GEN-LAST:event_btnfrapeActionPerformed

    private void btncobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobrarActionPerformed
        
    }//GEN-LAST:event_btncobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnamericano;
    private javax.swing.JButton btnbombon;
    private javax.swing.JButton btncapuchino;
    private javax.swing.JButton btncarajillo;
    private javax.swing.JButton btncobrar;
    private javax.swing.JButton btnconleche;
    private javax.swing.JButton btncortado;
    private javax.swing.JButton btnexpreso;
    private javax.swing.JButton btnfrape;
    private javax.swing.JButton btnirlandes;
    private javax.swing.JButton btnmocca;
    private javax.swing.JButton btnristretto;
    private javax.swing.JButton btnvienes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField txtingresarmonto;
    private javax.swing.JTextField txtmostrar;
    // End of variables declaration//GEN-END:variables
}
